#!/usr/bin/env bash
#
# optimize-mysql.sh — Generate safe MySQL/MariaDB tuning for THIS server's RAM.
#
# Sizes InnoDB buffers from detected memory, keeps a backup of the previous
# config, then restarts the database. Run as root. Safe to re-run.
#
set -euo pipefail

if [[ $EUID -ne 0 ]]; then
  echo "Run as root (sudo)." >&2
  exit 1
fi

# --- Detect service + config dir -------------------------------------------
if systemctl list-unit-files --type=service 2>/dev/null | grep -q '^mariadb\.service'; then
  SERVICE=mariadb
  CONF_DIR=/etc/mysql/mariadb.conf.d
else
  SERVICE=mysql
  CONF_DIR=/etc/mysql/conf.d
fi
OUT="${CONF_DIR}/99-autotune.cnf"

# --- Read total RAM in MB ----------------------------------------------------
MEM_MB=$(awk '/^MemTotal:/ { printf "%d", $2 / 1024 }' /proc/meminfo)
echo "Detected RAM: ${MEM_MB} MB"

# InnoDB buffer pool ~50% of RAM (the single most important setting),
# capped sensibly so tiny VPSs don't swap.
POOL_MB=$(( MEM_MB / 2 ))
(( POOL_MB < 128 )) && POOL_MB=128
(( POOL_MB > 4096 )) && POOL_MB=4096

KEY_BUF_MB=$(( MEM_MB / 16 ))
(( KEY_BUF_MB < 16 )) && KEY_BUF_MB=16
(( KEY_BUF_MB > 256 )) && KEY_BUF_MB=256

# Connections: ~20 per GB, capped — most WP sites need far fewer.
MAX_CONN=$(( MEM_MB / 50 ))
(( MAX_CONN < 50 )) && MAX_CONN=50
(( MAX_CONN > 300 )) && MAX_CONN=300

# --- Write config (backup first) ---------------------------------------------
if [[ -f "$OUT" ]]; then
  cp "$OUT" "${OUT}.bak.$(date +%Y%m%d%H%M%S)"
  echo "Backed up previous autotune config."
fi

cat > "$OUT" <<EOF
# Generated by optimize-mysql.sh on $(date -u +%F) — re-run anytime to retune.
[mysqld]
innodb_buffer_pool_size = ${POOL_MB}M
innodb_buffer_pool_instances = 1
key_buffer_size = ${KEY_BUF_MB}M
max_connections = ${MAX_CONN}
innodb_log_file_size = $(( POOL_MB / 4 ))M
query_cache_type = 0
query_cache_size = 0
# Slow-query log stays on so you can find bad queries:
slow_query_log = 1
long_query_time = 2
EOF

echo "Wrote ${OUT}:"
cat "$OUT"

# --- Restart -----------------------------------------------------------------
systemctl restart "$SERVICE"
echo "Restarted ${SERVICE}. Verify with: mysql -e 'SHOW VARIABLES LIKE \"innodb_buffer_pool_size\";'"
