#!/usr/bin/env bash
# renew-letsencrypt.sh — renew all Let's Encrypt certificates safely.
#
# Wraps `certbot renew` with a deploy hook, so your web server is reloaded
# ONLY when a certificate actually renews. Sends an email alert on failure.
# Designed for cron:
#
#   0 3 * * * /opt/scripts/renew-letsencrypt.sh --webserver nginx --email admin@example.com >> /var/log/letsencrypt-renew.log 2>&1
#
# Options:
#   --webserver nginx|apache|ols   which server to reload (default: nginx)
#   --email addr                   alert address on failure (default: none)
#   --dry-run                      test renewal without touching certs
#   --log FILE                     log file (default: /var/log/letsencrypt-renew.log)

set -u

WEBSERVER="nginx"
EMAIL=""
DRYRUN=0
LOGFILE="/var/log/letsencrypt-renew.log"

while [[ $# -gt 0 ]]; do
	case "$1" in
		--webserver) WEBSERVER="$2"; shift 2 ;;
		--email)     EMAIL="$2";     shift 2 ;;
		--dry-run)   DRYRUN=1;       shift ;;
		--log)       LOGFILE="$2";   shift 2 ;;
		*) echo "Unknown option: $1" >&2; exit 2 ;;
	esac
done

case "$WEBSERVER" in
	nginx|apache|ols) ;;
	*) echo "Invalid --webserver: $WEBSERVER (nginx|apache|ols)" >&2; exit 2 ;;
esac

if [[ $EUID -ne 0 ]]; then
	echo "This script must run as root (cron does that automatically)." >&2
	exit 1
fi

if ! command -v certbot >/dev/null 2>&1; then
	echo "certbot is not installed." >&2
	exit 1
fi

log() { echo "[$(date '+%F %T')] $*" | tee -a "$LOGFILE"; }

alert() {
	[[ -n "$EMAIL" ]] || return 0
	if command -v mail >/dev/null 2>&1; then
		echo "$1" | mail -s "[$(hostname)] Let's Encrypt renewal FAILED" "$EMAIL"
	elif command -v sendmail >/dev/null 2>&1; then
		{ echo "Subject: [$(hostname)] Let's Encrypt renewal FAILED"; echo; echo "$1"; } | sendmail "$EMAIL"
	fi
}

# Deploy hook: runs once per renewed cert lineage. Exported variables
# RENEWED_LINEAGE / RENEWED_DOMAINS come from certbot automatically.
build_hook() {
	local hook
	hook="$(mktemp /tmp/renew-letsencrypt-hook.XXXXXX)"
	cat > "$hook" <<'HOOK_EOF'
#!/usr/bin/env bash
# Auto-generated by renew-letsencrypt.sh — reloads the web server after renewal.
echo "[$(date '+%F %T')] certbot renewed: ${RENEWED_DOMAINS:-unknown} — reloading web server"
HOOK_EOF
	case "$WEBSERVER" in
		nginx)
			cat >> "$hook" <<'HOOK_EOF'
if nginx -t 2>/dev/null; then systemctl reload nginx; else echo "nginx config test FAILED — not reloaded" >&2; exit 1; fi
HOOK_EOF
			;;
		apache)
			cat >> "$hook" <<'HOOK_EOF'
if apachectl configtest 2>/dev/null; then systemctl reload apache2; else echo "apache config test FAILED — not reloaded" >&2; exit 1; fi
HOOK_EOF
			;;
		ols)
			cat >> "$hook" <<'HOOK_EOF'
if [[ -x /usr/local/lsws/bin/lswsctrl ]]; then /usr/local/lsws/bin/lswsctrl reload; else echo "lswsctrl not found — restart OpenLiteSpeed manually" >&2; exit 1; fi
HOOK_EOF
			;;
	esac
	chmod +x "$hook"
	echo "$hook"
}

HOOK="$(build_hook)"
trap 'rm -f "$HOOK"' EXIT

RENEW_ARGS=(renew --quiet --no-random-sleep-on-renew --deploy-hook "$HOOK")
(( DRYRUN )) && RENEW_ARGS+=(--dry-run)

log "Starting renewal (dry-run=$DRYRUN, webserver=$WEBSERVER)"
OUTPUT=$(certbot "${RENEW_ARGS[@]}" 2>&1)
STATUS=$?

if (( STATUS != 0 )); then
	log "RENEWAL FAILED (exit $STATUS):"
	echo "$OUTPUT" | tee -a "$LOGFILE"
	alert "certbot renew failed on $(hostname) (exit $STATUS):\n\n$OUTPUT"
	exit 1
fi

log "Renewal check OK (deploy hook reloads $WEBSERVER only when a cert actually renewed)"
