#!/usr/bin/env bash
#
# server-status.sh — generate a one-page HTML server health report.
#
#   sudo ./server-status.sh [output.html] [domain1 domain2 ...]
#
# Collects hostname, uptime, load, memory, disk, top processes, key service
# states, listening ports, and SSL certificate expiry for the given domains,
# then writes a self-contained HTML report. Handy as a daily cron email
# attachment or a quick "is the server healthy?" glance.
#
# Example cron (daily 8 AM, saved under /var/www/html for internal viewing):
#   0 8 * * * /opt/scripts/server-status.sh /var/www/html/status.html example.com

set -euo pipefail

OUT="${1:-/tmp/server-status.html}"
shift || true
DOMAINS=("$@")

HOST="$(hostname -f 2>/dev/null || hostname)"
DATE="$(date '+%Y-%m-%d %H:%M:%S %Z')"

# --- helpers ---------------------------------------------------------------

esc() { # HTML-escape stdin
    sed -e 's/&/\&amp;/g' -e 's/</\&lt;/g' -e 's/>/\&gt;/g'
}

row() { # row "Label" "value"
    printf '<tr><th>%s</th><td><pre>%s</pre></td></tr>\n' "$1" "$(printf '%s' "$2" | esc)"
}

svc() { # svc nginx -> "active" / "inactive" / "not installed"
    local s="$1"
    if ! systemctl list-unit-files --type=service 2>/dev/null | grep -q "^${s}\.service"; then
        echo "not installed"; return
    fi
    systemctl is-active "$s" 2>/dev/null || echo "unknown"
}

cert_days() { # cert_days example.com -> days until expiry, or an error string
    local d="$1" end epoch now
    end="$(echo | timeout 10 openssl s_client -servername "$d" -connect "$d:443" 2>/dev/null \
        | openssl x509 -noout -enddate 2>/dev/null | cut -d= -f2)"
    if [[ -z "$end" ]]; then echo "could not fetch certificate"; return; fi
    epoch="$(date -d "$end" +%s 2>/dev/null || echo 0)"
    now="$(date +%s)"
    echo "$(( (epoch - now) / 86400 )) days (expires $end)"
}

# --- collect ---------------------------------------------------------------

UPTIME="$(uptime)"
LOAD="$(cat /proc/loadavg | awk '{print $1", "$2", "$3" (1/5/15 min)"}')"
MEM="$(free -h | esc)"
DISK="$(df -h -x tmpfs -x devtmpfs | esc)"
TOPCPU="$(ps -eo pid,ppid,%cpu,%mem,comm --sort=-%cpu | head -11 | esc)"
TOPMEM="$(ps -eo pid,ppid,%cpu,%mem,comm --sort=-%mem | head -11 | esc)"
PORTS="$(ss -tlnp 2>/dev/null | head -30 | esc || echo 'ss not available')"

SERVICES=""
for s in nginx apache2 mysql mariadb php8.3-fpm php8.2-fpm php8.1-fpm redis-server fail2ban postfix dovecot docker; do
    st="$(svc "$s")"
    [[ "$st" == "not installed" ]] && continue
    SERVICES+="${s}: ${st}"$'\n'
done
[[ -z "$SERVICES" ]] && SERVICES="(none of the monitored services installed)"
SERVICES="$(printf '%s' "$SERVICES" | esc)"

CERTS=""
for d in "${DOMAINS[@]:-}"; do
    [[ -z "$d" ]] && continue
    CERTS+="${d}: $(cert_days "$d")"$'\n'
done
[[ -z "$CERTS" ]] && CERTS="(no domains checked — pass domain names as arguments)"
CERTS="$(printf '%s' "$CERTS" | esc)"

# --- render ----------------------------------------------------------------

{
cat <<EOF
<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8">
<title>Server status — $HOST</title>
<style>
body{font-family:system-ui,-apple-system,sans-serif;background:#0f172a;color:#e2e8f0;max-width:960px;margin:2rem auto;padding:0 1rem}
h1{font-size:1.4rem}table{width:100%;border-collapse:collapse;margin-bottom:1.5rem}
th,td{border:1px solid #334155;padding:.5rem .75rem;text-align:left;vertical-align:top}
th{width:220px;background:#1e293b}pre{margin:0;white-space:pre-wrap;font-size:.82rem}
.ok{color:#4ade80}.bad{color:#f87171}.meta{color:#94a3b8;font-size:.85rem}
</style></head><body>
<h1>🖥️ Server status — $(printf '%s' "$HOST" | esc)</h1>
<p class="meta">Generated $DATE</p>
<table>
$(row "Uptime" "$UPTIME")
$(row "Load average" "$LOAD")
$(row "Memory" "$MEM")
$(row "Disk usage" "$DISK")
$(row "Services" "$SERVICES")
$(row "Top processes by CPU" "$TOPCPU")
$(row "Top processes by memory" "$TOPMEM")
$(row "Listening ports" "$PORTS")
$(row "SSL certificate expiry" "$CERTS")
</table>
<p class="meta">Generated by server-status.sh (vps-setup-scripts). Keep this report private — it exposes service versions and ports.</p>
</body></html>
EOF
} > "$OUT"

echo "Report written to $OUT"
