#!/usr/bin/env bash
#
# tune-php-fpm.sh — auto-tune PHP-FPM pool + OPcache from detected RAM.
#
# Rewrites pm.* settings in the pool config and enables a production-grade
# OPcache config. Backs everything up first, dry-runs by default.
#
# Usage: sudo ./tune-php-fpm.sh [--pool www] [--yes]
#   --pool  pool config name without .conf (default: www)
#   --yes   apply changes without asking (default: show plan and confirm)
#
set -euo pipefail

POOL="www"
YES=0

while [ $# -gt 0 ]; do
    case "$1" in
        --pool) POOL="$2"; shift 2 ;;
        --yes)  YES=1; shift ;;
        *) echo "Unknown option: $1" >&2; exit 1 ;;
    esac
done

if [ "$(id -u)" -ne 0 ]; then
    echo "Run as root (sudo)." >&2
    exit 1
fi

# --- Detect RAM and compute pm values ----------------------------------------
# Rule of thumb: ~30MB per PHP-FPM child, reserve 1GB for OS + MySQL + nginx.
RAM_MB="$(awk '/MemTotal/ {printf "%.0f", $2/1024}' /proc/meminfo)"
RESERVE_MB=1024
if [ "$RAM_MB" -lt 2048 ]; then
    RESERVE_MB=512
fi
USABLE_MB=$(( RAM_MB - RESERVE_MB ))
[ "$USABLE_MB" -lt 256 ] && USABLE_MB=256

MAX_CHILDREN=$(( USABLE_MB / 30 ))
[ "$MAX_CHILDREN" -lt 4 ]  && MAX_CHILDREN=4
[ "$MAX_CHILDREN" -gt 100 ] && MAX_CHILDREN=100

# Dynamic process manager: start with half the children, spare within bounds.
START_SERVERS=$(( MAX_CHILDREN / 2 ))
MIN_SPARE=$(( MAX_CHILDREN / 4 ))
MAX_SPARE=$(( MAX_CHILDREN * 3 / 4 ))
[ "$MIN_SPARE" -lt 2 ] && MIN_SPARE=2
[ "$MAX_SPARE" -le "$MIN_SPARE" ] && MAX_SPARE=$(( MIN_SPARE + 2 ))

# --- Locate pool config --------------------------------------------------------
PHP_VER="$(php -v 2>/dev/null | head -1 | grep -oE '[0-9]+\.[0-9]+' | head -1 || true)"
POOL_FILE=""
for v in "$PHP_VER" "" ; do
    for f in "/etc/php/${v}/fpm/pool.d/${POOL}.conf"; do
        [ -f "$f" ] && POOL_FILE="$f" && break 2
    done
done
if [ -z "$POOL_FILE" ]; then
    POOL_FILE="$(find /etc/php -path "*/fpm/pool.d/${POOL}.conf" 2>/dev/null | head -1 || true)"
fi
if [ -z "$POOL_FILE" ]; then
    echo "Could not find pool config for '${POOL}' under /etc/php." >&2
    exit 1
fi

BACKUP="${POOL_FILE}.bak.$(date +%Y%m%d-%H%M%S)"

echo "RAM:            ${RAM_MB} MB (usable for PHP: ${USABLE_MB} MB)"
echo "Pool file:      ${POOL_FILE}"
echo "Backup:         ${BACKUP}"
echo ""
echo "Planned settings:"
echo "  pm                   = dynamic"
echo "  pm.max_children      = ${MAX_CHILDREN}"
echo "  pm.start_servers     = ${START_SERVERS}"
echo "  pm.min_spare_servers = ${MIN_SPARE}"
echo "  pm.max_spare_servers = ${MAX_SPARE}"
echo "  pm.max_requests      = 500   (recycle workers, fights memory leaks)"
echo "  OPcache: enabled, memory 128MB, validate timestamps on, revalidate every 60s"
echo ""

if [ "$YES" -ne 1 ]; then
    read -r -p "Apply these settings? [y/N] " ANSWER
    case "$ANSWER" in
        [Yy]*) ;;
        *) echo "Aborted. No changes made."; exit 0 ;;
    esac
fi

cp -a "$POOL_FILE" "$BACKUP"

set_kv() { # key value file
    if grep -qE "^;?\s*${1}\s*=" "$3"; then
        sed -i -E "s|^;?\s*${1}\s*=.*|${1} = ${2}|" "$3"
    else
        printf '%s = %s\n' "$1" "$2" >> "$3"
    fi
}

set_kv pm dynamic                       "$POOL_FILE"
set_kv pm.max_children "$MAX_CHILDREN"  "$POOL_FILE"
set_kv pm.start_servers "$START_SERVERS" "$POOL_FILE"
set_kv pm.min_spare_servers "$MIN_SPARE" "$POOL_FILE"
set_kv pm.max_spare_servers "$MAX_SPARE" "$POOL_FILE"
set_kv pm.max_requests 500              "$POOL_FILE"

# OPcache: production defaults in a conf.d drop-in.
OPCACHE_CONF="$(dirname "$(dirname "$POOL_FILE")")/conf.d/99-tuned-opcache.ini"
cat > "$OPCACHE_CONF" <<'EOF'
; Generated by tune-php-fpm.sh
opcache.enable=1
opcache.memory_consumption=128
opcache.interned_strings_buffer=16
opcache.max_accelerated_files=10000
opcache.validate_timestamps=1
opcache.revalidate_freq=60
opcache.save_comments=1
EOF
echo "Wrote ${OPCACHE_CONF}"

# Restart the matching php-fpm service.
SERVICE="$(systemctl list-units --type=service --state=running 2>/dev/null \
    | grep -oE 'php[0-9.]*-fpm\.service' | head -1 || true)"
if [ -n "$SERVICE" ]; then
    systemctl restart "$SERVICE"
    echo "Restarted ${SERVICE}."
else
    echo "WARNING: could not detect a running php*-fpm service; restart PHP-FPM manually." >&2
fi

echo "Done. Original pool config backed up to ${BACKUP}."
